//src/app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import FontAwesomeClient from "./components/FontAwesomeClient";

/* 👉 Cart imports */
import { CartProvider } from "../context/CartContext";
import CartDrawer from "./components/cart/CartDrawer";

/* ✅ AuthContext import */
import { AuthProvider } from "./context/AuthContext";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ingrammicro-surface",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.variable} suppressHydrationWarning>
      <body className="min-h-screen flex flex-col antialiased">
        {/* ✅ Cart Provider wraps the whole app */}
        <CartProvider>
          {/* ✅ AuthProvider wraps all components that need auth */}
          <AuthProvider>
            {/* ✅ Global Toaster */}
  <Toaster
    position="top-right"
    containerStyle={{ top: 60 }}
    toastOptions={{
      style: { marginRight: "20px" },
    }}
  />

            <FontAwesomeClient />

            {/* Header */}
            <Navbar />

            {/* ✅ Global Cart Drawer */}
            <CartDrawer />

            {/* Main content */}
            <main className="flex-grow">{children}</main>

            {/* Footer */}
            <Footer />
          </AuthProvider>
        </CartProvider>
      </body>
    </html>
  );
}
