import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import FontAwesomeClient from "./components/FontAwesomeClient";

/* 👉 Cart imports */
import { CartProvider } from "../context/CartContext";
import CartDrawer from "./components/cart/CartDrawer";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ingram-surface",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.variable} suppressHydrationWarning>
      <body className="min-h-screen flex flex-col antialiased">
        {/* ✅ Cart Provider wraps the whole app */}
        <CartProvider>
          <FontAwesomeClient />

          {/* Header */}
          <Navbar />

          {/* ✅ Global Cart Drawer */}
          <CartDrawer />

          {/* Main content */}
          <main className="flex-grow">{children}</main>

          {/* Footer */}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
